#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'



/opt/de_GWD/tcpTime

if [[ -s /opt/de_GWD/.repo/geosite.dat ]] && [[ -s /opt/de_GWD/.repo/geoip.dat ]] && [[ -s /opt/de_GWD/.repo/Domains.chn.txt ]]; then
  serverConnect1=$(curl -Is -m 5 google.com | grep 'HTTP')
  serverConnect2=$(curl -Is -m 5 youtube.com | grep 'HTTP')
  [[ -z $serverConnect1 ]] && [[ -z $serverConnect2 ]] && exit
fi

[[ $1 = "u" ]] && service cron stop

echo -e "${WHITE}[...]\c" && echo -e "\t${WHITE}Update CHN Domain & IP rules${cRES}\r\c"
checkSum(){
sha256sumL=$(sha256sum $1 2>/dev/null | awk '{print$1}')
if [[ $sha256sumL = $2 ]]; then 
  echo "true"
elif [[ $sha256sumL != $2 ]]; then
  echo "false"
fi
}

get_sha256(){
  local url="$1"
  local sum
  sum=$(curl -fsSLo- "$url" 2>/dev/null | awk '{print$1}')
  if [[ -z "$sum" ]]; then
    sum=$(curl -fsSLo- "https://ghproxy.net/$url" 2>/dev/null | awk '{print$1}')
  fi
  echo "$sum"
}

geosite_sha256sum=$(get_sha256 https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat.sha256sum)
geoip_sha256sum=$(get_sha256 https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat.sha256sum)
IPchnroute_sha256sum=$(get_sha256 https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute.sha256sum)
DomainsChn_sha256sum=$(get_sha256 https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.chn.txt.sha256sum)
DomainsApple_sha256sum=$(get_sha256 https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.apple.txt.sha256sum)
DomainsGames_sha256sum=$(get_sha256 https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.games.txt.sha256sum)
bogusNxdomain_sha256sum=$(get_sha256 https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/99-bogus-nxdomain.china.conf.sha256sum)

if [[ -z "$geosite_sha256sum" ]] || [[ $(checkSum /opt/de_GWD/.repo/geosite.dat "$geosite_sha256sum") = "false" ]]; then
rm -rf /tmp/geosite.dat
wget --show-progress -cqO /tmp/geosite.dat https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat || \
wget --show-progress -cqO /tmp/geosite.dat https://ghproxy.net/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat
  if [[ -n "$geosite_sha256sum" && $(checkSum /tmp/geosite.dat "$geosite_sha256sum") = "true" ]] || [[ -z "$geosite_sha256sum" && -s /tmp/geosite.dat ]]; then
    mv -f /tmp/geosite.dat /opt/de_GWD/.repo/geosite.dat
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}geosite.dat${RED} Download Failed${cRES}"
  fi
fi

if [[ -z "$geoip_sha256sum" ]] || [[ $(checkSum /opt/de_GWD/.repo/geoip.dat "$geoip_sha256sum") = "false" ]]; then
rm -rf /tmp/geoip.dat
wget --show-progress -cqO /tmp/geoip.dat https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat || \
wget --show-progress -cqO /tmp/geoip.dat https://ghproxy.net/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  if [[ -n "$geoip_sha256sum" && $(checkSum /tmp/geoip.dat "$geoip_sha256sum") = "true" ]] || [[ -z "$geoip_sha256sum" && -s /tmp/geoip.dat ]]; then
    mv -f /tmp/geoip.dat /opt/de_GWD/.repo/geoip.dat
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}geoip.dat${RED} Download Failed${cRES}"
  fi
fi

if [[ -z "$IPchnroute_sha256sum" ]] || [[ $(checkSum /opt/de_GWD/.repo/IPchnroute "$IPchnroute_sha256sum") = "false" ]]; then
rm -rf /tmp/IPchnroute
wget --show-progress -cqO /tmp/IPchnroute https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute || \
wget --show-progress -cqO /tmp/IPchnroute https://ghproxy.net/https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute
  if [[ -n "$IPchnroute_sha256sum" && $(checkSum /tmp/IPchnroute "$IPchnroute_sha256sum") = "true" ]] || [[ -z "$IPchnroute_sha256sum" && -s /tmp/IPchnroute ]]; then
    mv -f /tmp/IPchnroute /opt/de_GWD/.repo/IPchnroute
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}IPchnroute${RED} Download Failed${cRES}"
  fi
fi

if [[ -z "$DomainsChn_sha256sum" ]] || [[ $(checkSum /opt/de_GWD/.repo/Domains.chn.txt "$DomainsChn_sha256sum") = "false" ]]; then
rm -rf /tmp/Domains.chn.txt
wget --show-progress -cqO /tmp/Domains.chn.txt https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.chn.txt || \
wget --show-progress -cqO /tmp/Domains.chn.txt https://ghproxy.net/https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.chn.txt
  if [[ -n "$DomainsChn_sha256sum" && $(checkSum /tmp/Domains.chn.txt "$DomainsChn_sha256sum") = "true" ]] || [[ -z "$DomainsChn_sha256sum" && -s /tmp/Domains.chn.txt ]]; then
    mv -f /tmp/Domains.chn.txt /opt/de_GWD/.repo/Domains.chn.txt
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}Domains.chn.txt${RED} Download Failed${cRES}"
  fi
fi

if [[ -z "$DomainsApple_sha256sum" ]] || [[ $(checkSum /opt/de_GWD/.repo/Domains.apple.txt "$DomainsApple_sha256sum") = "false" ]]; then
rm -rf /tmp/Domains.apple.txt
wget --show-progress -cqO /tmp/Domains.apple.txt https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.apple.txt || \
wget --show-progress -cqO /tmp/Domains.apple.txt https://ghproxy.net/https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.apple.txt
  if [[ -n "$DomainsApple_sha256sum" && $(checkSum /tmp/Domains.apple.txt "$DomainsApple_sha256sum") = "true" ]] || [[ -z "$DomainsApple_sha256sum" && -s /tmp/Domains.apple.txt ]]; then
    mv -f /tmp/Domains.apple.txt /opt/de_GWD/.repo/Domains.apple.txt
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}Domains.apple.txt${RED} Download Failed${cRES}"
  fi
fi

if [[ -z "$DomainsGames_sha256sum" ]] || [[ $(checkSum /opt/de_GWD/.repo/Domains.games.txt "$DomainsGames_sha256sum") = "false" ]]; then
rm -rf /tmp/Domains.games.txt
wget --show-progress -cqO /tmp/Domains.games.txt https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.games.txt || \
wget --show-progress -cqO /tmp/Domains.games.txt https://ghproxy.net/https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/Domains.games.txt
  if [[ -n "$DomainsGames_sha256sum" && $(checkSum /tmp/Domains.games.txt "$DomainsGames_sha256sum") = "true" ]] || [[ -z "$DomainsGames_sha256sum" && -s /tmp/Domains.games.txt ]]; then
    mv -f /tmp/Domains.games.txt /opt/de_GWD/.repo/Domains.games.txt
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}Domains.games.txt${RED} Download Failed${cRES}"
  fi
fi

if [[ -z "$bogusNxdomain_sha256sum" ]] || [[ $(checkSum /opt/de_GWD/.repo/99-bogus-nxdomain.china.conf "$bogusNxdomain_sha256sum") = "false" ]]; then
rm -rf /tmp/99-bogus-nxdomain.china.conf
wget --show-progress -cqO /tmp/99-bogus-nxdomain.china.conf https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/99-bogus-nxdomain.china.conf || \
wget --show-progress -cqO /tmp/99-bogus-nxdomain.china.conf https://ghproxy.net/https://raw.githubusercontent.com/jacyl4/chnroute/main/mosdns_chnlist/99-bogus-nxdomain.china.conf
  if [[ -n "$bogusNxdomain_sha256sum" && $(checkSum /tmp/99-bogus-nxdomain.china.conf "$bogusNxdomain_sha256sum") = "true" ]] || [[ -z "$bogusNxdomain_sha256sum" && -s /tmp/99-bogus-nxdomain.china.conf ]]; then
    mv -f /tmp/99-bogus-nxdomain.china.conf /opt/de_GWD/.repo/99-bogus-nxdomain.china.conf
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}bogus-nxdomain.china.conf${RED} Download Failed${cRES}"
  fi
fi

if [[ -s /opt/de_GWD/.repo/99-bogus-nxdomain.china.conf ]]; then
  cp -f /opt/de_GWD/.repo/99-bogus-nxdomain.china.conf /etc/dnsmasq.d/
fi

if [[ -s /opt/de_GWD/.repo/geosite.dat ]]; then
  cp -f /opt/de_GWD/.repo/geosite.dat /opt/de_GWD/vtrui/geosite.dat
fi

if [[ -s /opt/de_GWD/.repo/geoip.dat ]]; then
  cp -f /opt/de_GWD/.repo/geoip.dat /opt/de_GWD/vtrui/geoip.dat
fi

if [[ -s /opt/de_GWD/.repo/IPchnroute ]]; then
cp -f /opt/de_GWD/.repo/IPchnroute /opt/de_GWD/nftables/IP_CHNROUTE
sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_CHNROUTE
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_CHNROUTE
nft flush set ip de_GWD CHNROUTE 2>/dev/null
cat << EOF >/opt/de_GWD/nftables/SET_CHNROUTE.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set CHNROUTE {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { $(cat /opt/de_GWD/nftables/IP_CHNROUTE) }
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_CHNROUTE.nft
/opt/de_GWD/nftables/SET_CHNROUTE.nft
fi

if [[ -n $(openssl x509 -enddate -noout -in /var/www/ssl/de_GWD.cer -checkend 259200 | grep "Certificate will expire") ]] && [[ -d "/root/.acme.sh" ]]; then
"/root/.acme.sh"/acme.sh --force --set-default-ca  --server letsencrypt
"/root/.acme.sh"/acme.sh --force --cron --home "/root/.acme.sh"

sslFolder=$(ls "/root/.acme.sh" | grep '_ecc')
cp -f "/root/.acme.sh"/$sslFolder/fullchain.cer /var/www/ssl/de_GWD.cer
cp -f "/root/.acme.sh"/$sslFolder/*.key /var/www/ssl/de_GWD.key
fi

[[ $1 = "u" ]] && service cron restart

echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Update CHN Domain & IP rules${cRES}"